import type { CatalogManifestRecord } from "@/domain/exercises/catalog-generator";

export const armsManifest = [
  {
    slug: "overhead-dumbbell-triceps-extension",
    name: "Overhead dumbbell triceps extension",
    role: "accessory",
    loggingKind: "weight_reps",
    requiredEquipment: ["dumbbells"],
    movementFamily: "overhead-triceps-extension",
    primaryMuscles: ["triceps"],
    aliases: ["DB overhead extension", "dumbbell French press"],
    instructions: [
      "Hold the dumbbell securely above the head.",
      "Keep the upper arms steady while lowering behind the head.",
      "Extend the elbows smoothly and stop before control changes.",
    ],
  },
  {
    slug: "dumbbell-curl",
    name: "Dumbbell curl",
    role: "accessory",
    loggingKind: "weight_reps",
    requiredEquipment: ["dumbbells"],
    movementFamily: "biceps-curl",
    primaryMuscles: ["biceps", "forearms"],
    aliases: ["DB biceps curl", "alternating dumbbell curl"],
    instructions: [
      "Stand tall with a dumbbell at each side.",
      "Curl without swinging or driving the elbows forward.",
      "Lower each weight to the start under control.",
    ],
  },
  {
    slug: "hammer-curl",
    name: "Hammer curl",
    role: "accessory",
    loggingKind: "weight_reps",
    requiredEquipment: ["dumbbells"],
    movementFamily: "biceps-curl",
    primaryMuscles: ["biceps", "forearms"],
    aliases: ["dumbbell hammer curl", "neutral-grip curl"],
    instructions: [
      "Stand tall with the palms facing inward and the dumbbells at the sides.",
      "Curl the weights without changing the neutral hand position.",
      "Lower to straight arms under control without swinging.",
    ],
  },
  {
    slug: "cross-body-hammer-curl",
    name: "Cross-body hammer curl",
    role: "accessory",
    loggingKind: "weight_reps",
    requiredEquipment: ["dumbbells"],
    movementFamily: "biceps-curl",
    primaryMuscles: ["biceps", "forearms"],
    aliases: ["cross-body dumbbell curl", "pinwheel curl"],
    instructions: [
      "Stand with the dumbbells at the sides and the palms facing inward.",
      "Curl one weight toward the opposite side of the chest without twisting the torso.",
      "Lower it under control, then repeat with the other arm.",
    ],
  },
  {
    slug: "incline-dumbbell-curl",
    name: "Incline dumbbell curl",
    role: "accessory",
    loggingKind: "weight_reps",
    requiredEquipment: ["dumbbells", "bench"],
    movementFamily: "biceps-curl",
    primaryMuscles: ["biceps", "forearms"],
    aliases: ["incline DB curl", "incline bench curl"],
    instructions: [
      "Sit against an inclined bench with the dumbbells hanging at the sides.",
      "Curl the weights while the upper arms remain behind the torso.",
      "Lower to a full arm reach without letting the shoulders roll forward.",
    ],
  },
  {
    slug: "concentration-curl",
    name: "Concentration curl",
    role: "accessory",
    loggingKind: "weight_reps",
    requiredEquipment: ["dumbbells", "bench"],
    movementFamily: "biceps-curl",
    primaryMuscles: ["biceps", "forearms"],
    aliases: ["seated concentration curl", "single-arm supported curl"],
    instructions: [
      "Sit on the bench and brace one upper arm against the inside of the thigh.",
      "Curl the dumbbell without lifting the braced elbow.",
      "Lower the weight slowly, finish the side, then switch arms.",
    ],
  },
  {
    slug: "barbell-curl",
    name: "Barbell curl",
    role: "accessory",
    loggingKind: "weight_reps",
    requiredEquipment: ["barbell", "plates"],
    movementFamily: "biceps-curl",
    primaryMuscles: ["biceps", "forearms"],
    aliases: ["standing barbell curl", "BB biceps curl"],
    instructions: [
      "Stand tall with an underhand grip and the bar against the thighs.",
      "Curl the bar while keeping the elbows near the sides.",
      "Lower the bar to straight arms without rocking the torso.",
    ],
  },
  {
    slug: "reverse-barbell-curl",
    name: "Reverse barbell curl",
    role: "accessory",
    loggingKind: "weight_reps",
    requiredEquipment: ["barbell", "plates"],
    movementFamily: "biceps-curl",
    primaryMuscles: ["forearms", "biceps"],
    aliases: ["overhand barbell curl", "pronated barbell curl"],
    instructions: [
      "Stand tall with an overhand grip and the bar against the thighs.",
      "Curl the bar while the wrists stay aligned with the forearms.",
      "Lower to straight arms under control without swinging.",
    ],
  },
  {
    slug: "lying-dumbbell-triceps-extension",
    name: "Lying dumbbell triceps extension",
    role: "accessory",
    loggingKind: "weight_reps",
    requiredEquipment: ["dumbbells", "bench"],
    movementFamily: "lying-triceps-extension",
    primaryMuscles: ["triceps"],
    aliases: ["dumbbell skull crusher", "lying DB extension"],
    instructions: [
      "Lie securely with the dumbbells above the shoulders and arms straight.",
      "Bend the elbows to lower the weights beside the head.",
      "Extend the elbows while keeping the upper arms steady.",
    ],
  },
  {
    slug: "barbell-skull-crusher",
    name: "Barbell skull crusher",
    role: "accessory",
    loggingKind: "weight_reps",
    requiredEquipment: ["barbell", "plates", "bench"],
    movementFamily: "lying-triceps-extension",
    primaryMuscles: ["triceps"],
    aliases: ["lying barbell triceps extension", "bench barbell triceps extension"],
    instructions: [
      "Lie securely with the bar held above the shoulders and arms straight.",
      "Keep the upper arms steady while bending the elbows to lower the bar.",
      "Extend the elbows smoothly and finish with the bar balanced.",
    ],
  },
  {
    slug: "dumbbell-triceps-kickback",
    name: "Dumbbell triceps kickback",
    role: "accessory",
    loggingKind: "weight_reps",
    requiredEquipment: ["dumbbells", "bench"],
    movementFamily: "triceps-kickback",
    primaryMuscles: ["triceps"],
    aliases: ["DB kickback", "dumbbell arm kickback"],
    instructions: [
      "Support one hand on the bench and hold the working upper arm beside the torso.",
      "Extend the elbow until the dumbbell travels behind the hip.",
      "Return the forearm under control, finish the side, then switch.",
    ],
  },
  {
    slug: "bench-dip",
    name: "Bench dip",
    role: "compound",
    loggingKind: "bodyweight_reps",
    requiredEquipment: ["bodyweight", "bench"],
    movementFamily: "dip",
    primaryMuscles: ["triceps", "pecs", "front deltoids"],
    aliases: ["triceps bench dip", "bench triceps dip"],
    instructions: [
      "Grip the bench edge beside the hips and place the feet securely forward.",
      "Bend the elbows to lower the torso close to the bench.",
      "Press through both hands to return to straight arms without swinging.",
    ],
  },
  {
    slug: "close-grip-dumbbell-press",
    name: "Close-grip dumbbell press",
    role: "compound",
    loggingKind: "weight_reps",
    requiredEquipment: ["dumbbells", "bench"],
    movementFamily: "close-grip-press",
    primaryMuscles: ["triceps", "pecs", "front deltoids"],
    aliases: ["narrow dumbbell bench press", "DB close-grip press"],
    instructions: [
      "Lie securely with the dumbbells close together above the chest.",
      "Lower the weights with the elbows tracking near the torso.",
      "Press to straight arms while keeping both weights balanced.",
    ],
  },
  {
    slug: "barbell-jm-press",
    name: "Barbell JM press",
    role: "compound",
    loggingKind: "weight_reps",
    requiredEquipment: ["barbell", "plates", "bench", "rack"],
    movementFamily: "jm-press",
    primaryMuscles: ["triceps", "pecs", "front deltoids"],
    aliases: ["JM press", "barbell triceps press"],
    instructions: [
      "Lie securely beneath the rack and hold the bar above the upper chest.",
      "Bend the elbows forward as the bar travels toward the chin and upper-chest line.",
      "Extend the elbows to press the bar back up before reracking.",
    ],
  },
] as const satisfies readonly CatalogManifestRecord[];
