import type { CatalogManifestRecord } from "@/domain/exercises/catalog-generator";

export const backAndRearShoulderManifest = [
  {
    slug: "barbell-bent-over-row",
    name: "Barbell bent-over row",
    role: "compound",
    loggingKind: "weight_reps",
    requiredEquipment: ["barbell", "plates"],
    movementFamily: "horizontal-row",
    primaryMuscles: ["lats", "upper back", "biceps"],
    aliases: ["barbell row", "bent row"],
    instructions: [
      "Set a stable torso position before starting the pull.",
      "Row the weight toward the ribs without using momentum.",
      "Lower to a controlled reach while keeping the setup steady.",
    ],
  },
  {
    slug: "one-arm-dumbbell-row",
    name: "One-arm dumbbell row",
    role: "compound",
    loggingKind: "weight_reps",
    requiredEquipment: ["dumbbells", "bench"],
    movementFamily: "one-arm-row",
    primaryMuscles: ["lats", "upper back", "biceps"],
    aliases: ["single-arm dumbbell row", "one-arm DB row"],
    instructions: [
      "Support one hand on the bench and set a stable stance.",
      "Pull the dumbbell toward the hip while the torso stays quiet.",
      "Lower to a controlled reach, finish the side, then switch.",
    ],
  },
  {
    slug: "dumbbell-pullover",
    name: "Dumbbell pullover",
    role: "accessory",
    loggingKind: "weight_reps",
    requiredEquipment: ["dumbbells", "bench"],
    movementFamily: "pullover",
    primaryMuscles: ["lats", "pecs", "triceps"],
    aliases: ["DB pullover", "bench pullover"],
    instructions: [
      "Lie securely on the bench and hold the dumbbell above the chest.",
      "Move the weight in an arc with softly bent elbows.",
      "Reverse the arc under control at the end of the chosen range.",
    ],
  },
  {
    slug: "chest-supported-dumbbell-row",
    name: "Chest-supported dumbbell row",
    role: "compound",
    loggingKind: "weight_reps",
    requiredEquipment: ["dumbbells", "bench"],
    movementFamily: "horizontal-row",
    primaryMuscles: ["lats", "upper back", "biceps"],
    aliases: [
      "incline bench dumbbell row",
      "chest-supported DB row",
      "prone dumbbell row",
    ],
    instructions: [
      "Set a stable torso position before starting the pull.",
      "Row the weight toward the ribs without using momentum.",
      "Lower to a controlled reach while keeping the setup steady.",
    ],
  },
  {
    slug: "pendlay-row",
    name: "Pendlay row",
    role: "compound",
    loggingKind: "weight_reps",
    requiredEquipment: ["barbell", "plates"],
    movementFamily: "horizontal-row",
    primaryMuscles: ["lats", "upper back", "biceps"],
    aliases: ["dead-stop barbell row", "Pendlay barbell row"],
    instructions: [
      "Hinge until the bar rests on the floor beneath the shoulders.",
      "Row the bar toward the lower ribs without lifting the torso.",
      "Return the bar to a complete stop and reset before the next repetition.",
    ],
  },
  {
    slug: "underhand-barbell-row",
    name: "Underhand barbell row",
    role: "compound",
    loggingKind: "weight_reps",
    requiredEquipment: ["barbell", "plates"],
    movementFamily: "horizontal-row",
    primaryMuscles: ["lats", "upper back", "biceps"],
    aliases: ["reverse-grip barbell row", "supinated barbell row"],
    instructions: [
      "Take an underhand grip and set a steady hip-hinged position.",
      "Pull the bar toward the lower ribs while the torso stays quiet.",
      "Lower the bar to a full arm reach without losing the hinge.",
    ],
  },
  {
    slug: "dumbbell-renegade-row",
    name: "Dumbbell renegade row",
    role: "compound",
    loggingKind: "weight_reps",
    requiredEquipment: ["dumbbells"],
    movementFamily: "renegade-row",
    primaryMuscles: ["lats", "upper back", "biceps", "core"],
    aliases: ["renegade row", "plank dumbbell row"],
    instructions: [
      "Set a wide-foot plank with each hand supported on a dumbbell.",
      "Row one weight toward the ribs while keeping the hips facing the floor.",
      "Replace the dumbbell with control before switching sides.",
    ],
  },
  {
    slug: "dumbbell-reverse-fly",
    name: "Dumbbell reverse fly",
    role: "accessory",
    loggingKind: "weight_reps",
    requiredEquipment: ["dumbbells"],
    movementFamily: "reverse-fly",
    primaryMuscles: ["rear deltoids", "upper back"],
    aliases: ["bent-over dumbbell fly", "DB reverse fly"],
    instructions: [
      "Hinge forward with a dumbbell hanging beneath each shoulder.",
      "Open the arms out to the sides with the elbows softly bent.",
      "Lower the weights together without changing the torso position.",
    ],
  },
  {
    slug: "dumbbell-rear-delt-row",
    name: "Dumbbell rear-delt row",
    role: "accessory",
    loggingKind: "weight_reps",
    requiredEquipment: ["dumbbells"],
    movementFamily: "rear-delt-row",
    primaryMuscles: ["rear deltoids", "upper back"],
    aliases: ["elbows-out dumbbell row", "DB rear-delt row"],
    instructions: [
      "Hinge forward and let the dumbbells hang beneath the shoulders.",
      "Row with the elbows angled out as the weights approach the sides of the upper chest.",
      "Lower to straight arms while keeping the torso still.",
    ],
  },
  {
    slug: "barbell-shrug",
    name: "Barbell shrug",
    role: "accessory",
    loggingKind: "weight_reps",
    requiredEquipment: ["barbell", "plates"],
    movementFamily: "shrug",
    primaryMuscles: ["traps", "upper back"],
    aliases: ["barbell shoulder shrug", "BB shrug"],
    instructions: [
      "Stand tall with the bar held against the front of the thighs.",
      "Lift both shoulders straight up without bending the elbows.",
      "Pause briefly, then lower the shoulders under control.",
    ],
  },
  {
    slug: "dumbbell-shrug",
    name: "Dumbbell shrug",
    role: "accessory",
    loggingKind: "weight_reps",
    requiredEquipment: ["dumbbells"],
    movementFamily: "shrug",
    primaryMuscles: ["traps", "upper back"],
    aliases: ["dumbbell shoulder shrug", "DB shrug"],
    instructions: [
      "Stand tall with a dumbbell resting at each side.",
      "Raise both shoulders straight up while keeping the arms long.",
      "Lower the shoulders slowly without rolling them forward or back.",
    ],
  },
  {
    slug: "inverted-row",
    name: "Inverted row",
    role: "compound",
    loggingKind: "bodyweight_reps",
    requiredEquipment: ["bodyweight", "barbell", "rack"],
    movementFamily: "inverted-row",
    primaryMuscles: ["lats", "upper back", "biceps"],
    aliases: ["bodyweight row", "rack row"],
    instructions: [
      "Secure the bar in the rack and hang beneath it with straight arms.",
      "Pull the chest toward the bar while the body travels as one line.",
      "Lower to a full arm reach without letting the hips drop.",
    ],
  },
  {
    slug: "dumbbell-dead-row",
    name: "Dumbbell dead row",
    role: "compound",
    loggingKind: "weight_reps",
    requiredEquipment: ["dumbbells"],
    movementFamily: "dead-stop-row",
    primaryMuscles: ["lats", "upper back", "biceps"],
    aliases: ["dead-stop dumbbell row", "DB dead row"],
    instructions: [
      "Hinge over the dumbbells and set the torso before each pull.",
      "Row both weights toward the ribs without using a leg drive.",
      "Lower the dumbbells to a complete stop and reset the hinge.",
    ],
  },
  {
    slug: "barbell-rack-pull",
    name: "Barbell rack pull",
    role: "compound",
    loggingKind: "weight_reps",
    requiredEquipment: ["barbell", "plates", "rack"],
    movementFamily: "rack-pull",
    primaryMuscles: ["glutes", "hamstrings", "upper back"],
    aliases: ["rack deadlift", "partial barbell deadlift"],
    instructions: [
      "Set the bar on the rack supports and stand with it close to the legs.",
      "Drive through the feet and extend the hips while the bar stays close.",
      "Return the bar to the supports under control before resetting.",
    ],
  },
  {
    slug: "dumbbell-high-pull",
    name: "Dumbbell high pull",
    role: "compound",
    loggingKind: "weight_reps",
    requiredEquipment: ["dumbbells"],
    movementFamily: "high-pull",
    primaryMuscles: ["traps", "deltoids", "glutes"],
    aliases: ["DB high pull", "two-dumbbell high pull"],
    instructions: [
      "Stand with the dumbbells in front of the thighs and hinge slightly.",
      "Extend the hips as the elbows lead the weights upward.",
      "Lower the dumbbells under control and reset before repeating.",
    ],
  },
] as const satisfies readonly CatalogManifestRecord[];
