import type { CatalogManifestRecord } from "@/domain/exercises/catalog-generator";

export const chestAndPushingManifest = [
  {
    slug: "dumbbell-bench-press",
    name: "Dumbbell bench press",
    role: "compound",
    loggingKind: "weight_reps",
    requiredEquipment: ["dumbbells", "bench"],
    movementFamily: "bench-press",
    primaryMuscles: ["pecs", "triceps", "front deltoids"],
    aliases: ["DB bench press", "dumbbell chest press"],
    instructions: [
      "Set a stable bench position with both feet planted.",
      "Lower the weight toward the mid-chest under control.",
      "Press along the same path and finish each repetition balanced.",
    ],
  },
  {
    slug: "incline-dumbbell-press",
    name: "Incline dumbbell press",
    role: "compound",
    loggingKind: "weight_reps",
    requiredEquipment: ["dumbbells", "bench"],
    movementFamily: "incline-press",
    primaryMuscles: ["upper pecs", "front deltoids", "triceps"],
    aliases: ["incline DB bench", "incline chest press"],
    instructions: [
      "Set the bench to a modest incline and plant both feet.",
      "Lower the weights beside the upper chest without bouncing.",
      "Press along the same path and keep the shoulders supported.",
    ],
  },
  {
    slug: "barbell-bench-press",
    name: "Barbell bench press",
    role: "compound",
    loggingKind: "weight_reps",
    requiredEquipment: ["barbell", "plates", "bench", "rack"],
    movementFamily: "bench-press",
    primaryMuscles: ["pecs", "triceps", "front deltoids"],
    aliases: ["bench press", "flat barbell bench"],
    instructions: [
      "Set a stable bench position with both feet planted.",
      "Lower the weight toward the mid-chest under control.",
      "Press along the same path and finish each repetition balanced.",
    ],
  },
  {
    slug: "push-up",
    name: "Push-up",
    role: "compound",
    loggingKind: "bodyweight_reps",
    requiredEquipment: ["bodyweight"],
    movementFamily: "push-up",
    primaryMuscles: ["pecs", "triceps", "front deltoids"],
    aliases: ["press-up", "standard push-up"],
    instructions: [
      "Start in a tall plank with the hands just wider than the shoulders.",
      "Lower the chest while the head, hips, and heels travel together.",
      "Press the floor away and finish with the body in one line.",
    ],
  },
  {
    slug: "incline-push-up",
    name: "Incline push-up",
    role: "compound",
    loggingKind: "bodyweight_reps",
    requiredEquipment: ["bodyweight", "bench"],
    movementFamily: "push-up",
    primaryMuscles: ["pecs", "triceps", "front deltoids"],
    aliases: ["bench push-up", "elevated push-up"],
    instructions: [
      "Place both hands securely on the bench and walk the feet back.",
      "Lower the chest toward the bench while keeping the body aligned.",
      "Press through the hands to return to the tall starting position.",
    ],
  },
  {
    slug: "decline-push-up",
    name: "Decline push-up",
    role: "compound",
    loggingKind: "bodyweight_reps",
    requiredEquipment: ["bodyweight", "bench"],
    movementFamily: "push-up",
    primaryMuscles: ["upper pecs", "triceps", "front deltoids"],
    aliases: ["feet-elevated push-up", "feet-up push-up"],
    instructions: [
      "Set both feet securely on the bench and place the hands on the floor.",
      "Lower the chest while keeping the hips level with the shoulders.",
      "Press the floor away without letting the body position change.",
    ],
  },
  {
    slug: "close-grip-push-up",
    name: "Close-grip push-up",
    role: "compound",
    loggingKind: "bodyweight_reps",
    requiredEquipment: ["bodyweight"],
    movementFamily: "push-up",
    primaryMuscles: ["triceps", "pecs", "front deltoids"],
    aliases: ["narrow push-up", "triceps push-up"],
    instructions: [
      "Set a tall plank with the hands narrower than shoulder width.",
      "Lower under control with the elbows tracking near the torso.",
      "Press back to the start while keeping the hips and shoulders aligned.",
    ],
  },
  {
    slug: "diamond-push-up",
    name: "Diamond push-up",
    role: "compound",
    loggingKind: "bodyweight_reps",
    requiredEquipment: ["bodyweight"],
    movementFamily: "push-up",
    primaryMuscles: ["triceps", "pecs", "front deltoids"],
    aliases: ["triangle push-up", "diamond press-up"],
    instructions: [
      "Place the hands close together beneath the chest in a comfortable diamond shape.",
      "Lower the torso as one unit with the elbows tracking back.",
      "Press evenly through both hands to return to the starting plank.",
    ],
  },
  {
    slug: "dumbbell-floor-press",
    name: "Dumbbell floor press",
    role: "compound",
    loggingKind: "weight_reps",
    requiredEquipment: ["dumbbells"],
    movementFamily: "floor-press",
    primaryMuscles: ["pecs", "triceps", "front deltoids"],
    aliases: ["DB floor press", "floor dumbbell press"],
    instructions: [
      "Lie on the floor with bent knees and the dumbbells over the chest.",
      "Lower the weights until the upper arms settle lightly on the floor.",
      "Press the dumbbells up evenly without lifting the torso.",
    ],
  },
  {
    slug: "dumbbell-squeeze-press",
    name: "Dumbbell squeeze press",
    role: "compound",
    loggingKind: "weight_reps",
    requiredEquipment: ["dumbbells", "bench"],
    movementFamily: "squeeze-press",
    primaryMuscles: ["pecs", "triceps", "front deltoids"],
    aliases: ["hex press", "dumbbell crush press"],
    instructions: [
      "Lie securely on the bench with the dumbbells touching above the chest.",
      "Keep the weights pressed together while lowering them toward the torso.",
      "Press along the same path and keep the dumbbells together throughout.",
    ],
  },
  {
    slug: "dumbbell-chest-fly",
    name: "Dumbbell chest fly",
    role: "accessory",
    loggingKind: "weight_reps",
    requiredEquipment: ["dumbbells", "bench"],
    movementFamily: "chest-fly",
    primaryMuscles: ["pecs", "front deltoids"],
    aliases: ["flat dumbbell fly", "DB chest fly"],
    instructions: [
      "Lie securely on the bench with the weights above the chest.",
      "Open the arms in a wide arc while keeping a soft elbow bend.",
      "Bring the weights back over the chest along the same controlled arc.",
    ],
  },
  {
    slug: "incline-dumbbell-fly",
    name: "Incline dumbbell fly",
    role: "accessory",
    loggingKind: "weight_reps",
    requiredEquipment: ["dumbbells", "bench"],
    movementFamily: "incline-fly",
    primaryMuscles: ["upper pecs", "front deltoids"],
    aliases: ["incline DB fly", "incline chest fly"],
    instructions: [
      "Set the bench to a modest incline and hold the weights above the chest.",
      "Open the arms in a controlled arc with the elbows softly bent.",
      "Reverse the arc before the shoulders leave the supported position.",
    ],
  },
  {
    slug: "incline-barbell-bench-press",
    name: "Incline barbell bench press",
    role: "compound",
    loggingKind: "weight_reps",
    requiredEquipment: ["barbell", "plates", "bench", "rack"],
    movementFamily: "incline-press",
    primaryMuscles: ["upper pecs", "front deltoids", "triceps"],
    aliases: ["incline bench press", "incline barbell press"],
    instructions: [
      "Set the bench to a modest incline beneath the racked bar.",
      "Lower the bar toward the upper chest with the wrists stacked.",
      "Press back to the start along a steady path before reracking.",
    ],
  },
  {
    slug: "close-grip-barbell-bench-press",
    name: "Close-grip barbell bench press",
    role: "compound",
    loggingKind: "weight_reps",
    requiredEquipment: ["barbell", "plates", "bench", "rack"],
    movementFamily: "bench-press",
    primaryMuscles: ["triceps", "pecs", "front deltoids"],
    aliases: ["close-grip bench press", "narrow-grip barbell bench"],
    instructions: [
      "Lie securely under the rack and take a comfortable narrow grip.",
      "Lower the bar toward the lower chest with the elbows tracking near the torso.",
      "Press the bar to the start and settle it before reracking.",
    ],
  },
  {
    slug: "barbell-floor-press",
    name: "Barbell floor press",
    role: "compound",
    loggingKind: "weight_reps",
    requiredEquipment: ["barbell", "plates", "rack"],
    movementFamily: "floor-press",
    primaryMuscles: ["pecs", "triceps", "front deltoids"],
    aliases: ["floor bench press", "barbell press from floor"],
    instructions: [
      "Lie beneath the racked bar with bent knees and a stable upper back.",
      "Lower the bar until the upper arms settle lightly on the floor.",
      "Press to straight arms under control before returning the bar to the rack.",
    ],
  },
] as const satisfies readonly CatalogManifestRecord[];
