import type { CatalogManifestRecord } from "@/domain/exercises/catalog-generator";

export const conditioningAndCarriesManifest = [
  {
    slug: "burpee",
    name: "Burpee",
    role: "compound",
    loggingKind: "bodyweight_reps",
    requiredEquipment: ["bodyweight"],
    movementFamily: "burpee",
    primaryMuscles: ["quads", "glutes", "chest", "shoulders"],
    aliases: ["bodyweight burpee", "squat thrust jump"],
    instructions: [
      "Stand with enough clear floor space for a plank.",
      "Place the hands down, move the feet to a plank, and complete a controlled push-up.",
      "Bring the feet forward and jump vertically to finish the repetition.",
    ],
  },
  {
    slug: "squat-thrust",
    name: "Squat thrust",
    role: "compound",
    loggingKind: "bodyweight_reps",
    requiredEquipment: ["bodyweight"],
    movementFamily: "squat-thrust",
    primaryMuscles: ["quads", "glutes", "core", "shoulders"],
    aliases: ["no-jump squat thrust", "plank squat thrust"],
    instructions: [
      "Stand with enough clear floor space for a plank.",
      "Place the hands down and move both feet back to a stable plank.",
      "Bring the feet forward and stand without adding a jump.",
    ],
  },
  {
    slug: "jumping-jack",
    name: "Jumping jack",
    role: "compound",
    loggingKind: "duration",
    requiredEquipment: ["bodyweight"],
    movementFamily: "jumping-jack",
    primaryMuscles: ["calves", "quads", "shoulders"],
    aliases: ["star jump jack", "jumping jacks"],
    instructions: [
      "Stand tall with feet together and arms at the sides.",
      "Jump the feet apart while raising the arms, then reverse the motion.",
      "End the interval before the landing rhythm or arm path changes.",
    ],
  },
  {
    slug: "high-knees",
    name: "High knees",
    role: "compound",
    loggingKind: "duration",
    requiredEquipment: ["bodyweight"],
    movementFamily: "high-knees",
    primaryMuscles: ["hip flexors", "quads", "calves"],
    aliases: ["running high knees", "high knee march"],
    instructions: [
      "Stand tall with arms ready to move beside the body.",
      "Alternate lifting each knee while landing with controlled steps.",
      "End the interval before the torso leans or the step height changes.",
    ],
  },
  {
    slug: "skater-hop",
    name: "Skater hop",
    role: "compound",
    loggingKind: "bodyweight_reps",
    requiredEquipment: ["bodyweight"],
    movementFamily: "lateral-hop",
    primaryMuscles: ["glutes", "quads", "calves"],
    aliases: ["lateral skater jump", "speed skater hop"],
    instructions: [
      "Stand on one leg with clear space to each side.",
      "Hop laterally to the other leg and settle the landing under control.",
      "Alternate sides and stop before the landings become unsteady.",
    ],
  },
  {
    slug: "dumbbell-thruster",
    name: "Dumbbell thruster",
    role: "compound",
    loggingKind: "weight_reps",
    requiredEquipment: ["dumbbells"],
    movementFamily: "thruster",
    primaryMuscles: ["quads", "glutes", "deltoids", "triceps"],
    aliases: ["dumbbell squat to press", "DB thruster"],
    instructions: [
      "Hold the dumbbells at shoulder height in a balanced squat stance.",
      "Squat under control, then stand and continue into an overhead press.",
      "Return the dumbbells to the shoulders before the next repetition.",
    ],
  },
  {
    slug: "dumbbell-clean",
    name: "Dumbbell clean",
    role: "compound",
    loggingKind: "weight_reps",
    requiredEquipment: ["dumbbells"],
    movementFamily: "clean",
    primaryMuscles: ["glutes", "quads", "upper back", "forearms"],
    aliases: ["DB clean", "dumbbell power clean"],
    instructions: [
      "Start with the dumbbells close to the legs in a hinged position.",
      "Stand and guide the dumbbells upward without swinging them away.",
      "Receive them at the shoulders, then lower under control before repeating.",
    ],
  },
  {
    slug: "dumbbell-clean-and-press",
    name: "Dumbbell clean and press",
    role: "compound",
    loggingKind: "weight_reps",
    requiredEquipment: ["dumbbells"],
    movementFamily: "clean-and-press",
    primaryMuscles: ["glutes", "quads", "deltoids", "triceps"],
    aliases: ["DB clean and press", "dumbbell clean to press"],
    instructions: [
      "Start with the dumbbells close to the legs in a hinged position.",
      "Guide the weights to the shoulders, settle them, and press overhead.",
      "Return to the shoulders and lower the weights under control.",
    ],
  },
  {
    slug: "dumbbell-snatch",
    name: "Dumbbell snatch",
    role: "compound",
    loggingKind: "weight_reps",
    requiredEquipment: ["dumbbells"],
    movementFamily: "snatch",
    primaryMuscles: ["glutes", "quads", "shoulders", "upper back"],
    aliases: ["one-arm dumbbell snatch", "DB snatch"],
    instructions: [
      "Set one dumbbell close to the body from a stable hinged position.",
      "Stand and guide the dumbbell upward in one path to an overhead finish.",
      "Lower it under control, finish the side, and then switch arms.",
    ],
  },
  {
    slug: "dumbbell-farmer-carry",
    name: "Dumbbell farmer carry",
    role: "accessory",
    loggingKind: "distance_duration",
    requiredEquipment: ["dumbbells"],
    movementFamily: "loaded-carry",
    primaryMuscles: ["forearms", "core", "upper back"],
    aliases: ["farmers walk", "two-dumbbell carry"],
    instructions: [
      "Stand tall with one dumbbell held securely at each side.",
      "Walk the planned route with even steps and quiet weights.",
      "Set both dumbbells down under control at the end of the route.",
    ],
  },
  {
    slug: "dumbbell-suitcase-carry",
    name: "Dumbbell suitcase carry",
    role: "accessory",
    loggingKind: "distance_duration",
    requiredEquipment: ["dumbbells"],
    movementFamily: "loaded-carry",
    primaryMuscles: ["forearms", "core", "upper back"],
    aliases: ["one-arm suitcase walk", "single-dumbbell carry"],
    instructions: [
      "Stand tall with one dumbbell held securely beside the body.",
      "Walk the planned route without leaning toward or away from the weight.",
      "Set the dumbbell down under control and repeat on the other side.",
    ],
  },
  {
    slug: "dumbbell-front-rack-carry",
    name: "Dumbbell front-rack carry",
    role: "accessory",
    loggingKind: "distance_duration",
    requiredEquipment: ["dumbbells"],
    movementFamily: "loaded-carry",
    primaryMuscles: ["core", "upper back", "shoulders"],
    aliases: ["front rack walk", "dumbbell rack carry"],
    instructions: [
      "Hold both dumbbells securely at shoulder height with elbows supported.",
      "Walk the planned route with even steps and a steady torso.",
      "Lower both dumbbells under control at the end of the route.",
    ],
  },
  {
    slug: "bear-crawl",
    name: "Bear crawl",
    role: "compound",
    loggingKind: "distance_duration",
    requiredEquipment: ["bodyweight"],
    movementFamily: "bear-crawl",
    primaryMuscles: ["shoulders", "core", "quads"],
    aliases: ["forward bear crawl", "quadruped crawl"],
    instructions: [
      "Start on hands and feet with knees hovering close to the floor.",
      "Move the opposite hand and foot forward in short controlled steps.",
      "Finish the planned route before the knee height or torso position changes.",
    ],
  },
  {
    slug: "reverse-bear-crawl",
    name: "Reverse bear crawl",
    role: "compound",
    loggingKind: "distance_duration",
    requiredEquipment: ["bodyweight"],
    movementFamily: "bear-crawl",
    primaryMuscles: ["shoulders", "core", "quads"],
    aliases: ["backward bear crawl", "reverse quadruped crawl"],
    instructions: [
      "Start on hands and feet with knees hovering close to the floor.",
      "Move the opposite hand and foot backward in short controlled steps.",
      "Finish the planned route before the knee height or torso position changes.",
    ],
  },
] as const satisfies readonly CatalogManifestRecord[];
