import type { CatalogManifestRecord } from "@/domain/exercises/catalog-generator";

export const coreManifest = [
  {
    slug: "dead-bug",
    name: "Dead bug",
    role: "core-reps",
    loggingKind: "bodyweight_reps",
    requiredEquipment: ["bodyweight"],
    movementFamily: "dead-bug",
    primaryMuscles: ["core", "hip flexors"],
    aliases: ["alternating dead bug", "opposite arm leg lower"],
    instructions: [
      "Lie on the back with arms up and knees over the hips.",
      "Lower one arm and the opposite leg without rushing.",
      "Return to the start and alternate while the torso stays steady.",
    ],
  },
  {
    slug: "front-plank",
    name: "Front plank",
    role: "core-timed",
    loggingKind: "duration",
    requiredEquipment: ["bodyweight"],
    movementFamily: "front-plank",
    primaryMuscles: ["core", "glutes", "shoulders"],
    aliases: ["prone plank", "plank hold"],
    instructions: [
      "Place the forearms under the shoulders and extend both legs.",
      "Form one long line from head through heels.",
      "Breathe steadily and end the hold before position changes.",
    ],
  },
  {
    slug: "bird-dog",
    name: "Bird dog",
    role: "core-reps",
    loggingKind: "bodyweight_reps",
    requiredEquipment: ["bodyweight"],
    movementFamily: "bird-dog",
    primaryMuscles: ["core", "glutes", "upper back"],
    aliases: ["quadruped reach", "opposite arm leg reach"],
    instructions: [
      "Start on hands and knees with hands under shoulders.",
      "Reach one arm and the opposite leg away from the body.",
      "Return without shifting the torso, then alternate sides.",
    ],
  },
  {
    slug: "side-plank",
    name: "Side plank",
    role: "core-timed",
    loggingKind: "duration",
    requiredEquipment: ["bodyweight"],
    movementFamily: "side-plank",
    primaryMuscles: ["obliques", "glutes", "shoulders"],
    aliases: ["lateral plank", "side plank hold"],
    instructions: [
      "Place one forearm under the shoulder and set the feet.",
      "Lift the hips into a straight line from head to feet.",
      "Hold with steady breathing, then repeat on the other side.",
    ],
  },
  {
    slug: "plank-shoulder-tap",
    name: "Plank shoulder tap",
    role: "core-reps",
    loggingKind: "bodyweight_reps",
    requiredEquipment: ["bodyweight"],
    movementFamily: "shoulder-tap",
    primaryMuscles: ["core", "shoulders", "triceps"],
    aliases: ["high plank shoulder tap", "plank taps"],
    instructions: [
      "Start in a high plank with a stable foot position.",
      "Lift one hand to tap the opposite shoulder.",
      "Replace the hand and alternate while limiting torso rotation.",
    ],
  },
  {
    slug: "reverse-crunch",
    name: "Reverse crunch",
    role: "core-reps",
    loggingKind: "bodyweight_reps",
    requiredEquipment: ["bodyweight"],
    movementFamily: "reverse-crunch",
    primaryMuscles: ["core", "hip flexors"],
    aliases: ["lying reverse crunch", "knee tuck crunch"],
    instructions: [
      "Lie on the back with knees bent and feet lifted.",
      "Bring the knees toward the torso with a small controlled curl.",
      "Lower until the pelvis returns without using momentum.",
    ],
  },
  {
    slug: "bicycle-crunch",
    name: "Bicycle crunch",
    role: "core-reps",
    loggingKind: "bodyweight_reps",
    requiredEquipment: ["bodyweight"],
    movementFamily: "bicycle-crunch",
    primaryMuscles: ["core", "obliques", "hip flexors"],
    aliases: ["bicycle abs", "alternating elbow knee crunch"],
    instructions: [
      "Lie on the back with hands lightly supporting the head.",
      "Rotate one shoulder toward the opposite bent knee.",
      "Alternate sides at a controlled pace without pulling the head.",
    ],
  },
  {
    slug: "hollow-hold",
    name: "Hollow hold",
    role: "core-timed",
    loggingKind: "duration",
    requiredEquipment: ["bodyweight"],
    movementFamily: "hollow-hold",
    primaryMuscles: ["core", "hip flexors"],
    aliases: ["hollow body hold", "dish hold"],
    instructions: [
      "Lie on the back and lift the shoulders and bent legs.",
      "Reach farther only while the torso stays steady.",
      "Hold with even breathing and use a tucked shape when needed.",
    ],
  },
] as const satisfies readonly CatalogManifestRecord[];
