import type { CatalogManifestRecord } from "@/domain/exercises/catalog-generator";

export const coreManifest = [
  {
    slug: "dead-bug",
    name: "Dead bug",
    role: "core-reps",
    loggingKind: "bodyweight_reps",
    requiredEquipment: ["bodyweight"],
    movementFamily: "dead-bug",
    primaryMuscles: ["core", "hip flexors"],
    aliases: ["alternating dead bug", "opposite arm leg lower"],
    instructions: [
      "Lie on the back with arms up and knees over the hips.",
      "Lower one arm and the opposite leg without rushing.",
      "Return to the start and alternate while the torso stays steady.",
    ],
  },
  {
    slug: "front-plank",
    name: "Front plank",
    role: "core-timed",
    loggingKind: "duration",
    requiredEquipment: ["bodyweight"],
    movementFamily: "front-plank",
    primaryMuscles: ["core", "glutes", "shoulders"],
    aliases: ["prone plank", "plank hold"],
    instructions: [
      "Place the forearms under the shoulders and extend both legs.",
      "Form one long line from head through heels.",
      "Breathe steadily and end the hold before position changes.",
    ],
  },
  {
    slug: "bird-dog",
    name: "Bird dog",
    role: "core-reps",
    loggingKind: "bodyweight_reps",
    requiredEquipment: ["bodyweight"],
    movementFamily: "bird-dog",
    primaryMuscles: ["core", "glutes", "upper back"],
    aliases: ["quadruped reach", "opposite arm leg reach"],
    instructions: [
      "Start on hands and knees with hands under shoulders.",
      "Reach one arm and the opposite leg away from the body.",
      "Return without shifting the torso, then alternate sides.",
    ],
  },
  {
    slug: "side-plank",
    name: "Side plank",
    role: "core-timed",
    loggingKind: "duration",
    requiredEquipment: ["bodyweight"],
    movementFamily: "side-plank",
    primaryMuscles: ["obliques", "glutes", "shoulders"],
    aliases: ["lateral plank", "side plank hold"],
    instructions: [
      "Place one forearm under the shoulder and set the feet.",
      "Lift the hips into a straight line from head to feet.",
      "Hold with steady breathing, then repeat on the other side.",
    ],
  },
  {
    slug: "plank-shoulder-tap",
    name: "Plank shoulder tap",
    role: "core-reps",
    loggingKind: "bodyweight_reps",
    requiredEquipment: ["bodyweight"],
    movementFamily: "shoulder-tap",
    primaryMuscles: ["core", "shoulders", "triceps"],
    aliases: ["high plank shoulder tap", "plank taps"],
    instructions: [
      "Start in a high plank with a stable foot position.",
      "Lift one hand to tap the opposite shoulder.",
      "Replace the hand and alternate while limiting torso rotation.",
    ],
  },
  {
    slug: "reverse-crunch",
    name: "Reverse crunch",
    role: "core-reps",
    loggingKind: "bodyweight_reps",
    requiredEquipment: ["bodyweight"],
    movementFamily: "reverse-crunch",
    primaryMuscles: ["core", "hip flexors"],
    aliases: ["lying reverse crunch", "knee tuck crunch"],
    instructions: [
      "Lie on the back with knees bent and feet lifted.",
      "Bring the knees toward the torso with a small controlled curl.",
      "Lower until the pelvis returns without using momentum.",
    ],
  },
  {
    slug: "bicycle-crunch",
    name: "Bicycle crunch",
    role: "core-reps",
    loggingKind: "bodyweight_reps",
    requiredEquipment: ["bodyweight"],
    movementFamily: "bicycle-crunch",
    primaryMuscles: ["core", "obliques", "hip flexors"],
    aliases: ["bicycle abs", "alternating elbow knee crunch"],
    instructions: [
      "Lie on the back with hands lightly supporting the head.",
      "Rotate one shoulder toward the opposite bent knee.",
      "Alternate sides at a controlled pace without pulling the head.",
    ],
  },
  {
    slug: "hollow-hold",
    name: "Hollow hold",
    role: "core-timed",
    loggingKind: "duration",
    requiredEquipment: ["bodyweight"],
    movementFamily: "hollow-hold",
    primaryMuscles: ["core", "hip flexors"],
    aliases: ["hollow body hold", "dish hold"],
    instructions: [
      "Lie on the back and lift the shoulders and bent legs.",
      "Reach farther only while the torso stays steady.",
      "Hold with even breathing and use a tucked shape when needed.",
    ],
  },
  {
    slug: "crunch",
    name: "Crunch",
    role: "core-reps",
    loggingKind: "bodyweight_reps",
    requiredEquipment: ["bodyweight"],
    movementFamily: "crunch",
    primaryMuscles: ["core"],
    aliases: ["ab crunch", "floor crunch"],
    instructions: [
      "Lie on the back with knees bent and feet planted.",
      "Lift the shoulder blades a short distance with a controlled curl.",
      "Lower the shoulders to the floor before the next repetition.",
    ],
  },
  {
    slug: "sit-up",
    name: "Sit-up",
    role: "core-reps",
    loggingKind: "bodyweight_reps",
    requiredEquipment: ["bodyweight"],
    movementFamily: "sit-up",
    primaryMuscles: ["core", "hip flexors"],
    aliases: ["full sit-up", "floor sit-up"],
    instructions: [
      "Lie on the back with knees bent and feet planted.",
      "Raise the torso toward an upright seated position without rushing.",
      "Lower the torso under control until the back returns to the floor.",
    ],
  },
  {
    slug: "heel-tap",
    name: "Heel tap",
    role: "core-reps",
    loggingKind: "bodyweight_reps",
    requiredEquipment: ["bodyweight"],
    movementFamily: "heel-tap",
    primaryMuscles: ["core", "obliques"],
    aliases: ["side heel tap", "heel touch"],
    instructions: [
      "Lie on the back with knees bent, feet planted, and shoulders lifted slightly.",
      "Reach one hand toward the same-side heel with a small side bend.",
      "Return through the center and alternate sides without dropping the shoulders.",
    ],
  },
  {
    slug: "toe-touch",
    name: "Toe touch",
    role: "core-reps",
    loggingKind: "bodyweight_reps",
    requiredEquipment: ["bodyweight"],
    movementFamily: "toe-touch",
    primaryMuscles: ["core", "hip flexors"],
    aliases: ["lying toe touch", "vertical leg toe reach"],
    instructions: [
      "Lie on the back with both legs raised and arms reaching upward.",
      "Curl the shoulders from the floor and reach toward the feet.",
      "Lower the shoulders under control while the legs stay steady.",
    ],
  },
  {
    slug: "lying-leg-raise",
    name: "Lying leg raise",
    role: "core-reps",
    loggingKind: "bodyweight_reps",
    requiredEquipment: ["bodyweight"],
    movementFamily: "leg-raise",
    primaryMuscles: ["core", "hip flexors"],
    aliases: ["straight-leg raise", "lying straight leg raise"],
    instructions: [
      "Lie on the back with both legs straight and together.",
      "Raise the legs as one unit without swinging them.",
      "Lower the legs slowly and end the range before the torso shifts.",
    ],
  },
  {
    slug: "bent-knee-leg-raise",
    name: "Bent-knee leg raise",
    role: "core-reps",
    loggingKind: "bodyweight_reps",
    requiredEquipment: ["bodyweight"],
    movementFamily: "leg-raise",
    primaryMuscles: ["core", "hip flexors"],
    aliases: ["bent-leg raise", "lying knee raise"],
    instructions: [
      "Lie on the back with knees bent and feet lifted together.",
      "Raise the bent legs toward the torso with a controlled motion.",
      "Lower the feet toward the floor and stop before the torso shifts.",
    ],
  },
  {
    slug: "flutter-kick",
    name: "Flutter kick",
    role: "core-timed",
    loggingKind: "duration",
    requiredEquipment: ["bodyweight"],
    movementFamily: "flutter-kick",
    primaryMuscles: ["core", "hip flexors"],
    aliases: ["alternating leg flutter", "flutter kicks"],
    instructions: [
      "Lie on the back with straight legs raised slightly from the floor.",
      "Alternate small up-and-down leg motions at a controlled pace.",
      "End the interval before the legs or torso lose their steady position.",
    ],
  },
  {
    slug: "scissor-kick",
    name: "Scissor kick",
    role: "core-timed",
    loggingKind: "duration",
    requiredEquipment: ["bodyweight"],
    movementFamily: "scissor-kick",
    primaryMuscles: ["core", "hip flexors", "adductors"],
    aliases: ["crossing leg kick", "scissor kicks"],
    instructions: [
      "Lie on the back with straight legs raised slightly from the floor.",
      "Cross one leg over the other and alternate the crossing pattern.",
      "End the interval before the leg height or torso position changes.",
    ],
  },
  {
    slug: "mountain-climber",
    name: "Mountain climber",
    role: "core-reps",
    loggingKind: "bodyweight_reps",
    requiredEquipment: ["bodyweight"],
    movementFamily: "mountain-climber",
    primaryMuscles: ["core", "hip flexors", "shoulders"],
    aliases: ["plank knee drive", "mountain climbers"],
    instructions: [
      "Start in a high plank with hands under the shoulders.",
      "Drive one knee toward the same-side elbow while the torso stays steady.",
      "Return the foot and alternate sides without shortening the plank.",
    ],
  },
  {
    slug: "cross-body-mountain-climber",
    name: "Cross-body mountain climber",
    role: "core-reps",
    loggingKind: "bodyweight_reps",
    requiredEquipment: ["bodyweight"],
    movementFamily: "mountain-climber",
    primaryMuscles: ["core", "obliques", "shoulders"],
    aliases: ["cross mountain climber", "opposite elbow knee climber"],
    instructions: [
      "Start in a high plank with hands under the shoulders.",
      "Drive one knee toward the opposite elbow with controlled rotation.",
      "Return the foot and alternate sides while the shoulders stay supported.",
    ],
  },
  {
    slug: "russian-twist",
    name: "Russian twist",
    role: "core-reps",
    loggingKind: "bodyweight_reps",
    requiredEquipment: ["bodyweight"],
    movementFamily: "seated-rotation",
    primaryMuscles: ["core", "obliques", "hip flexors"],
    aliases: ["seated torso twist", "bodyweight russian twist"],
    instructions: [
      "Sit with knees bent and lean the torso back to a steady angle.",
      "Rotate the ribs and hands toward one side without swinging.",
      "Pass through the center and alternate sides at the same pace.",
    ],
  },
  {
    slug: "v-up",
    name: "V-up",
    role: "core-reps",
    loggingKind: "bodyweight_reps",
    requiredEquipment: ["bodyweight"],
    movementFamily: "v-up",
    primaryMuscles: ["core", "hip flexors"],
    aliases: ["jackknife sit-up", "straight-leg v up"],
    instructions: [
      "Lie long with straight legs and arms reaching overhead.",
      "Raise the torso and legs together while reaching toward the feet.",
      "Lower both under control until the body returns to the start.",
    ],
  },
  {
    slug: "tuck-up",
    name: "Tuck-up",
    role: "core-reps",
    loggingKind: "bodyweight_reps",
    requiredEquipment: ["bodyweight"],
    movementFamily: "tuck-up",
    primaryMuscles: ["core", "hip flexors"],
    aliases: ["knee tuck up", "bent-knee v up"],
    instructions: [
      "Lie on the back with legs extended and arms reaching away.",
      "Lift the torso while drawing both knees toward the chest.",
      "Extend the body under control and stop before the limbs rest.",
    ],
  },
  {
    slug: "superman-hold",
    name: "Superman hold",
    role: "core-timed",
    loggingKind: "duration",
    requiredEquipment: ["bodyweight"],
    movementFamily: "prone-extension-hold",
    primaryMuscles: ["lower back", "glutes", "upper back"],
    aliases: ["prone superman hold", "superman isometric"],
    instructions: [
      "Lie face down with arms reaching forward and legs extended.",
      "Lift the arms, chest, and legs into a controlled hover.",
      "End the hold before the raised position or steady breathing changes.",
    ],
  },
  {
    slug: "bear-plank",
    name: "Bear plank",
    role: "core-timed",
    loggingKind: "duration",
    requiredEquipment: ["bodyweight"],
    movementFamily: "bear-plank",
    primaryMuscles: ["core", "shoulders", "quads"],
    aliases: ["bear hover", "quadruped knee hover"],
    instructions: [
      "Start on hands and knees with hands under shoulders and knees under hips.",
      "Lift both knees slightly while keeping the back steady.",
      "End the hold before the knees rise or the torso shifts.",
    ],
  },
  {
    slug: "plank-up-down",
    name: "Plank up-down",
    role: "core-reps",
    loggingKind: "bodyweight_reps",
    requiredEquipment: ["bodyweight"],
    movementFamily: "plank-up-down",
    primaryMuscles: ["core", "shoulders", "triceps"],
    aliases: ["plank walk-up", "forearm to high plank"],
    instructions: [
      "Start in a forearm plank with elbows under the shoulders.",
      "Press one hand and then the other into a high plank.",
      "Lower one forearm at a time and alternate the leading arm.",
    ],
  },
  {
    slug: "side-plank-reach-through",
    name: "Side plank reach-through",
    role: "core-reps",
    loggingKind: "bodyweight_reps",
    requiredEquipment: ["bodyweight"],
    movementFamily: "side-plank",
    primaryMuscles: ["obliques", "shoulders", "glutes"],
    aliases: ["threaded side plank", "side plank rotation"],
    instructions: [
      "Set a side plank with the supporting forearm under the shoulder.",
      "Reach the top arm beneath the torso with controlled rotation.",
      "Open back to the start, finish the side, and then switch sides.",
    ],
  },
  {
    slug: "dead-bug-heel-tap",
    name: "Dead bug heel tap",
    role: "core-reps",
    loggingKind: "bodyweight_reps",
    requiredEquipment: ["bodyweight"],
    movementFamily: "dead-bug",
    primaryMuscles: ["core", "hip flexors"],
    aliases: ["dead bug toe tap", "supine alternating heel tap"],
    instructions: [
      "Lie on the back with knees bent over the hips and arms raised.",
      "Lower one bent leg until the heel lightly taps the floor.",
      "Return the knee over the hip and alternate without shifting the torso.",
    ],
  },
] as const satisfies readonly CatalogManifestRecord[];
