import type { CatalogManifestRecord } from "@/domain/exercises/catalog-generator";

export const lowerBodyAndGlutesManifest = [
  {
    slug: "goblet-squat",
    name: "Goblet squat",
    role: "compound",
    loggingKind: "weight_reps",
    requiredEquipment: ["dumbbells"],
    movementFamily: "squat",
    primaryMuscles: ["quads", "glutes", "adductors"],
    aliases: ["dumbbell goblet squat", "cup squat"],
    instructions: [
      "Set a balanced stance with the whole foot planted.",
      "Descend between the hips while keeping the load controlled.",
      "Stand smoothly and finish each repetition balanced.",
    ],
  },
  {
    slug: "dumbbell-romanian-deadlift",
    name: "Dumbbell Romanian deadlift",
    role: "compound",
    loggingKind: "weight_reps",
    requiredEquipment: ["dumbbells"],
    movementFamily: "romanian-deadlift",
    primaryMuscles: ["hamstrings", "glutes", "upper back"],
    aliases: ["dumbbell RDL", "DB Romanian deadlift"],
    instructions: [
      "Start tall with the load close and knees softly bent.",
      "Push the hips back while keeping the weight near the legs.",
      "Reverse the hinge to stand without turning it into a squat.",
    ],
  },
  {
    slug: "reverse-lunge",
    name: "Reverse lunge",
    role: "compound",
    loggingKind: "weight_reps",
    requiredEquipment: ["dumbbells"],
    movementFamily: "lunge",
    primaryMuscles: ["quads", "glutes", "adductors"],
    aliases: ["backward lunge", "dumbbell reverse lunge"],
    instructions: [
      "Stand tall with the dumbbells at the sides.",
      "Step back and lower with control over the front leg.",
      "Push through the front foot to return, then repeat or alternate.",
    ],
  },
  {
    slug: "standing-calf-raise",
    name: "Standing calf raise",
    role: "accessory",
    loggingKind: "weight_reps",
    requiredEquipment: ["dumbbells"],
    movementFamily: "calf-raise",
    primaryMuscles: ["calves"],
    aliases: ["dumbbell calf raise", "standing heel raise"],
    instructions: [
      "Stand balanced with the weights at the sides.",
      "Rise onto the balls of the feet without rocking forward.",
      "Pause at the top and lower the heels slowly.",
    ],
  },
  {
    slug: "barbell-back-squat",
    name: "Barbell back squat",
    role: "compound",
    loggingKind: "weight_reps",
    requiredEquipment: ["barbell", "plates", "rack"],
    movementFamily: "squat",
    primaryMuscles: ["quads", "glutes", "adductors"],
    aliases: ["back squat", "rack squat"],
    instructions: [
      "Set a balanced stance with the whole foot planted.",
      "Descend between the hips while keeping the load controlled.",
      "Stand smoothly and finish each repetition balanced.",
    ],
  },
  {
    slug: "barbell-romanian-deadlift",
    name: "Barbell Romanian deadlift",
    role: "compound",
    loggingKind: "weight_reps",
    requiredEquipment: ["barbell", "plates"],
    movementFamily: "romanian-deadlift",
    primaryMuscles: ["hamstrings", "glutes", "upper back"],
    aliases: ["barbell RDL", "Romanian deadlift"],
    instructions: [
      "Start tall with the load close and knees softly bent.",
      "Push the hips back while keeping the weight near the legs.",
      "Reverse the hinge to stand without turning it into a squat.",
    ],
  },
  {
    slug: "bulgarian-split-squat",
    name: "Bulgarian split squat",
    role: "compound",
    loggingKind: "weight_reps",
    requiredEquipment: ["dumbbells", "bench"],
    movementFamily: "split-squat",
    primaryMuscles: ["quads", "glutes", "adductors"],
    aliases: ["rear-foot-elevated split squat", "RFESS"],
    instructions: [
      "Set the rear foot on the bench and stabilize the front foot.",
      "Lower through the front leg while keeping balance over the stance.",
      "Stand through the front foot, finish the side, then switch.",
    ],
  },
  {
    slug: "barbell-hip-thrust",
    name: "Barbell hip thrust",
    role: "compound",
    loggingKind: "weight_reps",
    requiredEquipment: ["barbell", "plates", "bench"],
    movementFamily: "hip-thrust",
    primaryMuscles: ["glutes", "hamstrings"],
    aliases: ["barbell glute bridge", "bench hip thrust"],
    instructions: [
      "Set the upper back against the bench and secure the load at the hips.",
      "Drive through the planted feet to lift the hips.",
      "Pause at a level top position, then lower under control.",
    ],
  },
  {
    slug: "dumbbell-hip-thrust",
    name: "Dumbbell hip thrust",
    role: "compound",
    loggingKind: "weight_reps",
    requiredEquipment: ["dumbbells", "bench"],
    movementFamily: "hip-thrust",
    primaryMuscles: ["glutes", "hamstrings"],
    aliases: ["weighted glute bridge", "dumbbell glute bridge"],
    instructions: [
      "Set the upper back against the bench and secure the load at the hips.",
      "Drive through the planted feet to lift the hips.",
      "Pause at a level top position, then lower under control.",
    ],
  },
] as const satisfies readonly CatalogManifestRecord[];
