import type { CatalogManifestRecord } from "@/domain/exercises/catalog-generator";

export const lowerBodyAndGlutesManifest = [
  {
    slug: "goblet-squat",
    name: "Goblet squat",
    role: "compound",
    loggingKind: "weight_reps",
    requiredEquipment: ["dumbbells"],
    movementFamily: "squat",
    primaryMuscles: ["quads", "glutes", "adductors"],
    aliases: ["dumbbell goblet squat", "cup squat"],
    instructions: [
      "Set a balanced stance with the whole foot planted.",
      "Descend between the hips while keeping the load controlled.",
      "Stand smoothly and finish each repetition balanced.",
    ],
  },
  {
    slug: "dumbbell-romanian-deadlift",
    name: "Dumbbell Romanian deadlift",
    role: "compound",
    loggingKind: "weight_reps",
    requiredEquipment: ["dumbbells"],
    movementFamily: "romanian-deadlift",
    primaryMuscles: ["hamstrings", "glutes", "upper back"],
    aliases: ["dumbbell RDL", "DB Romanian deadlift"],
    instructions: [
      "Start tall with the load close and knees softly bent.",
      "Push the hips back while keeping the weight near the legs.",
      "Reverse the hinge to stand without turning it into a squat.",
    ],
  },
  {
    slug: "reverse-lunge",
    name: "Reverse lunge",
    role: "compound",
    loggingKind: "weight_reps",
    requiredEquipment: ["dumbbells"],
    movementFamily: "lunge",
    primaryMuscles: ["quads", "glutes", "adductors"],
    aliases: ["backward lunge", "dumbbell reverse lunge"],
    instructions: [
      "Stand tall with the dumbbells at the sides.",
      "Step back and lower with control over the front leg.",
      "Push through the front foot to return, then repeat or alternate.",
    ],
  },
  {
    slug: "standing-calf-raise",
    name: "Standing calf raise",
    role: "accessory",
    loggingKind: "weight_reps",
    requiredEquipment: ["dumbbells"],
    movementFamily: "calf-raise",
    primaryMuscles: ["calves"],
    aliases: ["dumbbell calf raise", "standing heel raise"],
    instructions: [
      "Stand balanced with the weights at the sides.",
      "Rise onto the balls of the feet without rocking forward.",
      "Pause at the top and lower the heels slowly.",
    ],
  },
  {
    slug: "barbell-back-squat",
    name: "Barbell back squat",
    role: "compound",
    loggingKind: "weight_reps",
    requiredEquipment: ["barbell", "plates", "rack"],
    movementFamily: "squat",
    primaryMuscles: ["quads", "glutes", "adductors"],
    aliases: ["back squat", "rack squat"],
    instructions: [
      "Set a balanced stance with the whole foot planted.",
      "Descend between the hips while keeping the load controlled.",
      "Stand smoothly and finish each repetition balanced.",
    ],
  },
  {
    slug: "barbell-romanian-deadlift",
    name: "Barbell Romanian deadlift",
    role: "compound",
    loggingKind: "weight_reps",
    requiredEquipment: ["barbell", "plates"],
    movementFamily: "romanian-deadlift",
    primaryMuscles: ["hamstrings", "glutes", "upper back"],
    aliases: ["barbell RDL", "Romanian deadlift"],
    instructions: [
      "Start tall with the load close and knees softly bent.",
      "Push the hips back while keeping the weight near the legs.",
      "Reverse the hinge to stand without turning it into a squat.",
    ],
  },
  {
    slug: "bulgarian-split-squat",
    name: "Bulgarian split squat",
    role: "compound",
    loggingKind: "weight_reps",
    requiredEquipment: ["dumbbells", "bench"],
    movementFamily: "split-squat",
    primaryMuscles: ["quads", "glutes", "adductors"],
    aliases: ["rear-foot-elevated split squat", "RFESS"],
    instructions: [
      "Set the rear foot on the bench and stabilize the front foot.",
      "Lower through the front leg while keeping balance over the stance.",
      "Stand through the front foot, finish the side, then switch.",
    ],
  },
  {
    slug: "barbell-hip-thrust",
    name: "Barbell hip thrust",
    role: "compound",
    loggingKind: "weight_reps",
    requiredEquipment: ["barbell", "plates", "bench"],
    movementFamily: "hip-thrust",
    primaryMuscles: ["glutes", "hamstrings"],
    aliases: ["barbell glute bridge", "bench hip thrust"],
    instructions: [
      "Set the upper back against the bench and secure the load at the hips.",
      "Drive through the planted feet to lift the hips.",
      "Pause at a level top position, then lower under control.",
    ],
  },
  {
    slug: "dumbbell-hip-thrust",
    name: "Dumbbell hip thrust",
    role: "compound",
    loggingKind: "weight_reps",
    requiredEquipment: ["dumbbells", "bench"],
    movementFamily: "hip-thrust",
    primaryMuscles: ["glutes", "hamstrings"],
    aliases: ["weighted glute bridge", "dumbbell glute bridge"],
    instructions: [
      "Set the upper back against the bench and secure the load at the hips.",
      "Drive through the planted feet to lift the hips.",
      "Pause at a level top position, then lower under control.",
    ],
  },
  {
    slug: "barbell-front-squat",
    name: "Barbell front squat",
    role: "compound",
    loggingKind: "weight_reps",
    requiredEquipment: ["barbell", "plates", "rack"],
    movementFamily: "squat",
    primaryMuscles: ["quads", "glutes", "adductors"],
    aliases: ["front squat", "front-rack squat"],
    instructions: [
      "Unrack the bar across the front of the shoulders and set a balanced stance.",
      "Descend between the hips while keeping the elbows lifted.",
      "Stand through the whole foot and settle before reracking.",
    ],
  },
  {
    slug: "zercher-squat",
    name: "Zercher squat",
    role: "compound",
    loggingKind: "weight_reps",
    requiredEquipment: ["barbell", "plates", "rack"],
    movementFamily: "squat",
    primaryMuscles: ["quads", "glutes", "adductors", "upper back"],
    aliases: ["Zercher barbell squat", "elbow-cradle squat"],
    instructions: [
      "Cradle the racked bar in the elbows and clasp the hands securely.",
      "Squat between the hips while keeping the bar close to the torso.",
      "Stand smoothly and stabilize the bar before returning it to the rack.",
    ],
  },
  {
    slug: "sumo-goblet-squat",
    name: "Sumo goblet squat",
    role: "compound",
    loggingKind: "weight_reps",
    requiredEquipment: ["dumbbells"],
    movementFamily: "squat",
    primaryMuscles: ["quads", "glutes", "adductors"],
    aliases: ["wide-stance goblet squat", "dumbbell sumo squat"],
    instructions: [
      "Hold one dumbbell at the chest and set a comfortable wide stance.",
      "Sit down between the hips while the knees track with the feet.",
      "Stand through the whole foot and finish balanced.",
    ],
  },
  {
    slug: "dumbbell-split-squat",
    name: "Dumbbell split squat",
    role: "compound",
    loggingKind: "weight_reps",
    requiredEquipment: ["dumbbells"],
    movementFamily: "split-squat",
    primaryMuscles: ["quads", "glutes", "adductors"],
    aliases: ["stationary dumbbell lunge", "DB split squat"],
    instructions: [
      "Set a staggered stance with the dumbbells held at the sides.",
      "Lower straight down while keeping both feet in place.",
      "Stand through the front foot, finish the side, then switch.",
    ],
  },
  {
    slug: "forward-lunge",
    name: "Forward lunge",
    role: "compound",
    loggingKind: "weight_reps",
    requiredEquipment: ["dumbbells"],
    movementFamily: "lunge",
    primaryMuscles: ["quads", "glutes", "adductors"],
    aliases: ["dumbbell forward lunge", "front lunge"],
    instructions: [
      "Stand tall with the dumbbells held at the sides.",
      "Step forward and lower under control over the lead leg.",
      "Push back to the starting stance, then repeat or alternate.",
    ],
  },
  {
    slug: "walking-lunge",
    name: "Walking lunge",
    role: "compound",
    loggingKind: "weight_reps",
    requiredEquipment: ["dumbbells"],
    movementFamily: "lunge",
    primaryMuscles: ["quads", "glutes", "adductors"],
    aliases: ["dumbbell walking lunge", "walking dumbbell lunge"],
    instructions: [
      "Stand tall with room ahead and the dumbbells held at the sides.",
      "Step into a lunge and lower with the lead foot fully planted.",
      "Drive forward to bring the rear leg into the next controlled step.",
    ],
  },
  {
    slug: "lateral-lunge",
    name: "Lateral lunge",
    role: "compound",
    loggingKind: "weight_reps",
    requiredEquipment: ["dumbbells"],
    movementFamily: "lunge",
    primaryMuscles: ["adductors", "glutes", "quads"],
    aliases: ["dumbbell side lunge", "side lunge"],
    instructions: [
      "Stand tall with the dumbbells held in front of the thighs.",
      "Step to the side and sit into the stepping hip while the other leg stays long.",
      "Push through the stepping foot to return, then finish the side or alternate.",
    ],
  },
  {
    slug: "dumbbell-step-up",
    name: "Dumbbell step-up",
    role: "compound",
    loggingKind: "weight_reps",
    requiredEquipment: ["dumbbells", "bench"],
    movementFamily: "step-up",
    primaryMuscles: ["quads", "glutes"],
    aliases: ["weighted bench step-up", "DB step-up"],
    instructions: [
      "Place one whole foot securely on the bench with the dumbbells at the sides.",
      "Drive through the raised foot to stand on the bench without jumping.",
      "Step down under control, finish the side, then switch.",
    ],
  },
  {
    slug: "lateral-step-up",
    name: "Lateral step-up",
    role: "compound",
    loggingKind: "weight_reps",
    requiredEquipment: ["dumbbells", "bench"],
    movementFamily: "step-up",
    primaryMuscles: ["quads", "glutes", "adductors"],
    aliases: ["side step-up", "dumbbell lateral step-up"],
    instructions: [
      "Stand beside the bench with the inside foot planted on top.",
      "Drive through the raised foot to step up while the dumbbells stay quiet.",
      "Lower to the floor under control, finish the side, then switch.",
    ],
  },
  {
    slug: "single-leg-dumbbell-romanian-deadlift",
    name: "Single-leg dumbbell Romanian deadlift",
    role: "compound",
    loggingKind: "weight_reps",
    requiredEquipment: ["dumbbells"],
    movementFamily: "romanian-deadlift",
    primaryMuscles: ["hamstrings", "glutes", "upper back"],
    aliases: ["single-leg dumbbell RDL", "one-leg DB deadlift"],
    instructions: [
      "Balance on one softly bent leg with the dumbbells close to the body.",
      "Hinge at the hip as the free leg reaches back and the weights lower.",
      "Return to standing under control, finish the side, then switch.",
    ],
  },
  {
    slug: "dumbbell-stiff-leg-deadlift",
    name: "Dumbbell stiff-leg deadlift",
    role: "compound",
    loggingKind: "weight_reps",
    requiredEquipment: ["dumbbells"],
    movementFamily: "stiff-leg-deadlift",
    primaryMuscles: ["hamstrings", "glutes", "upper back"],
    aliases: ["DB stiff-leg deadlift", "dumbbell straight-leg deadlift"],
    instructions: [
      "Stand tall with the dumbbells close and only a slight knee bend.",
      "Push the hips back while lowering the weights along the legs.",
      "Reverse the hinge to stand without turning the movement into a squat.",
    ],
  },
  {
    slug: "conventional-barbell-deadlift",
    name: "Conventional barbell deadlift",
    role: "compound",
    loggingKind: "weight_reps",
    requiredEquipment: ["barbell", "plates"],
    movementFamily: "deadlift",
    primaryMuscles: ["glutes", "hamstrings", "upper back"],
    aliases: ["conventional deadlift", "barbell deadlift"],
    instructions: [
      "Stand with the bar over the middle of the feet and take a secure grip.",
      "Push through the floor as the hips and shoulders rise together.",
      "Return the bar close to the legs and settle it before resetting.",
    ],
  },
  {
    slug: "sumo-barbell-deadlift",
    name: "Sumo barbell deadlift",
    role: "compound",
    loggingKind: "weight_reps",
    requiredEquipment: ["barbell", "plates"],
    movementFamily: "deadlift",
    primaryMuscles: ["glutes", "adductors", "quads", "upper back"],
    aliases: ["sumo deadlift", "wide-stance barbell deadlift"],
    instructions: [
      "Set a wide stance around the bar and grip it inside the knees.",
      "Push through the feet and stand while the bar stays close.",
      "Lower the bar under control and reset the wide stance before repeating.",
    ],
  },
  {
    slug: "barbell-good-morning",
    name: "Barbell good morning",
    role: "compound",
    loggingKind: "weight_reps",
    requiredEquipment: ["barbell", "plates", "rack"],
    movementFamily: "good-morning",
    primaryMuscles: ["hamstrings", "glutes", "upper back"],
    aliases: ["good morning", "standing barbell good morning"],
    instructions: [
      "Unrack the bar across the upper back and set a softly bent stance.",
      "Push the hips back while the torso inclines as one steady unit.",
      "Reverse the hinge to stand tall before returning the bar to the rack.",
    ],
  },
  {
    slug: "bodyweight-glute-bridge",
    name: "Bodyweight glute bridge",
    role: "compound",
    loggingKind: "bodyweight_reps",
    requiredEquipment: ["bodyweight"],
    movementFamily: "glute-bridge",
    primaryMuscles: ["glutes", "hamstrings"],
    aliases: ["floor glute bridge", "bodyweight hip bridge"],
    instructions: [
      "Lie on the floor with bent knees and both feet planted.",
      "Drive through the feet to lift the hips without arching the torso.",
      "Pause in a level top position, then lower under control.",
    ],
  },
  {
    slug: "single-leg-glute-bridge",
    name: "Single-leg glute bridge",
    role: "compound",
    loggingKind: "bodyweight_reps",
    requiredEquipment: ["bodyweight"],
    movementFamily: "glute-bridge",
    primaryMuscles: ["glutes", "hamstrings"],
    aliases: ["one-leg glute bridge", "single-leg hip bridge"],
    instructions: [
      "Lie with one foot planted and the other leg held clear of the floor.",
      "Drive through the planted foot to raise the hips without twisting.",
      "Lower under control, finish the side, then switch legs.",
    ],
  },
  {
    slug: "frog-pump",
    name: "Frog pump",
    role: "accessory",
    loggingKind: "bodyweight_reps",
    requiredEquipment: ["bodyweight"],
    movementFamily: "glute-bridge",
    primaryMuscles: ["glutes", "adductors"],
    aliases: ["frog glute bridge", "butterfly glute bridge"],
    instructions: [
      "Lie on the floor with the soles together and the knees opened outward.",
      "Drive the hips upward while the soles of the feet stay together.",
      "Pause at the top and lower the hips under control.",
    ],
  },
  {
    slug: "seated-dumbbell-calf-raise",
    name: "Seated dumbbell calf raise",
    role: "accessory",
    loggingKind: "weight_reps",
    requiredEquipment: ["dumbbells", "bench"],
    movementFamily: "calf-raise",
    primaryMuscles: ["calves"],
    aliases: ["seated calf raise", "dumbbell seated heel raise"],
    instructions: [
      "Sit on the bench with the feet planted and dumbbells secured on the thighs.",
      "Raise the heels while keeping the balls of the feet in place.",
      "Pause briefly, then lower the heels slowly.",
    ],
  },
  {
    slug: "single-leg-calf-raise",
    name: "Single-leg calf raise",
    role: "accessory",
    loggingKind: "bodyweight_reps",
    requiredEquipment: ["bodyweight"],
    movementFamily: "calf-raise",
    primaryMuscles: ["calves"],
    aliases: ["one-leg calf raise", "single-leg heel raise"],
    instructions: [
      "Balance on one foot with the standing leg long and steady.",
      "Rise onto the ball of the foot without tipping the body forward.",
      "Lower the heel slowly, finish the side, then switch.",
    ],
  },
  {
    slug: "wall-sit",
    name: "Wall sit",
    role: "accessory",
    loggingKind: "duration",
    requiredEquipment: ["bodyweight"],
    movementFamily: "wall-sit",
    primaryMuscles: ["quads", "glutes"],
    aliases: ["wall squat hold", "static wall sit"],
    instructions: [
      "Place the back against a wall and walk the feet forward.",
      "Slide down to a steady squat position with both feet planted.",
      "Hold the chosen position while keeping the back supported and breathing evenly.",
    ],
  },
] as const satisfies readonly CatalogManifestRecord[];
