import type { CatalogManifestRecord } from "@/domain/exercises/catalog-generator";

export const mobilityAndRecoveryManifest = [
  {
    slug: "cat-cow",
    name: "Cat-cow",
    role: "accessory",
    loggingKind: "bodyweight_reps",
    requiredEquipment: ["bodyweight"],
    movementFamily: "spinal-flexion-extension",
    primaryMuscles: ["core", "upper back", "lower back"],
    aliases: ["cat cow stretch", "quadruped spinal wave"],
    instructions: [
      "Start on hands and knees with hands under shoulders and knees under hips.",
      "Alternate rounding the back and opening the chest with a slow motion.",
      "Return through a neutral position between each direction.",
    ],
  },
  {
    slug: "childs-pose",
    name: "Child's pose",
    role: "accessory",
    loggingKind: "duration",
    requiredEquipment: ["bodyweight"],
    movementFamily: "childs-pose",
    primaryMuscles: ["lats", "upper back", "glutes"],
    aliases: ["child pose", "kneeling rest stretch"],
    instructions: [
      "Kneel with the hips moving toward the heels and arms reaching forward.",
      "Settle the torso between or over the thighs without forcing the reach.",
      "End the hold slowly and return to hands and knees.",
    ],
  },
  {
    slug: "half-kneeling-thoracic-rotation",
    name: "Half-kneeling thoracic rotation",
    role: "accessory",
    loggingKind: "bodyweight_reps",
    requiredEquipment: ["bodyweight"],
    movementFamily: "thoracic-rotation",
    primaryMuscles: ["upper back", "obliques"],
    aliases: ["half-kneeling upper-back rotation", "half-kneeling T-spine rotation"],
    instructions: [
      "Set a half-kneeling stance with the torso tall and hands together.",
      "Rotate the upper torso toward the front-leg side without shifting the hips.",
      "Return to the start, finish the side, and then change legs.",
    ],
  },
  {
    slug: "kneeling-hip-flexor-stretch",
    name: "Kneeling hip flexor stretch",
    role: "accessory",
    loggingKind: "duration",
    requiredEquipment: ["bodyweight"],
    movementFamily: "hip-flexor-stretch",
    primaryMuscles: ["hip flexors", "quads", "glutes"],
    aliases: ["half-kneeling hip stretch", "kneeling lunge stretch"],
    instructions: [
      "Set a half-kneeling stance with the front foot planted.",
      "Shift the hips forward slightly while the torso stays tall.",
      "End the hold under control and repeat with the other leg forward.",
    ],
  },
  {
    slug: "seated-hamstring-stretch",
    name: "Seated hamstring stretch",
    role: "accessory",
    loggingKind: "duration",
    requiredEquipment: ["bodyweight"],
    movementFamily: "hamstring-stretch",
    primaryMuscles: ["hamstrings", "calves"],
    aliases: ["seated forward leg stretch", "seated straight-leg stretch"],
    instructions: [
      "Sit with one or both legs extended and the torso upright.",
      "Hinge forward from the hips while keeping the extended legs steady.",
      "End the hold slowly and repeat the setup on the other side when needed.",
    ],
  },
  {
    slug: "ninety-ninety-hip-switch",
    name: "90/90 hip switch",
    role: "accessory",
    loggingKind: "bodyweight_reps",
    requiredEquipment: ["bodyweight"],
    movementFamily: "hip-rotation",
    primaryMuscles: ["glutes", "hip rotators", "adductors"],
    aliases: ["ninety ninety hip switch", "seated hip rotation switch"],
    instructions: [
      "Sit with both knees bent and feet wider than the hips.",
      "Lower both knees toward one side while the feet stay planted.",
      "Return through the center and alternate sides without rushing.",
    ],
  },
  {
    slug: "figure-four-stretch",
    name: "Figure-four stretch",
    role: "accessory",
    loggingKind: "duration",
    requiredEquipment: ["bodyweight"],
    movementFamily: "hip-rotation",
    primaryMuscles: ["glutes", "hip rotators"],
    aliases: ["figure 4 hip stretch", "crossed-ankle glute stretch"],
    instructions: [
      "Lie on the back and cross one ankle over the opposite thigh.",
      "Draw the supporting leg inward while the crossed knee stays open.",
      "Release the hold under control and repeat on the other side.",
    ],
  },
  {
    slug: "standing-calf-stretch",
    name: "Standing calf stretch",
    role: "accessory",
    loggingKind: "duration",
    requiredEquipment: ["bodyweight"],
    movementFamily: "calf-stretch",
    primaryMuscles: ["calves"],
    aliases: ["wall calf stretch", "standing heel-down stretch"],
    instructions: [
      "Stand in a staggered stance with the back foot pointing forward.",
      "Shift toward the front leg while the back heel stays planted.",
      "End the hold under control and repeat with the other leg back.",
    ],
  },
  {
    slug: "shoulder-wall-slide",
    name: "Shoulder wall slide",
    role: "accessory",
    loggingKind: "bodyweight_reps",
    requiredEquipment: ["bodyweight"],
    movementFamily: "shoulder-wall-slide",
    primaryMuscles: ["upper back", "deltoids", "rotator cuff"],
    aliases: ["back-to-wall shoulder slide", "standing wall slide"],
    instructions: [
      "Stand with your back against a wall, elbows bent, and arms supported.",
      "Slide the arms upward only while their path stays controlled.",
      "Lower the arms to the start before the next repetition.",
    ],
  },
  {
    slug: "prone-cobra",
    name: "Prone cobra",
    role: "accessory",
    loggingKind: "duration",
    requiredEquipment: ["bodyweight"],
    movementFamily: "prone-cobra",
    primaryMuscles: ["upper back", "lower back", "shoulders"],
    aliases: ["floor prone cobra", "prone chest raise"],
    instructions: [
      "Lie face down with legs extended and arms resting beside the body.",
      "Lift the chest slightly while reaching the arms back and keeping the legs down.",
      "End the hold before the chest height or head position changes.",
    ],
  },
] as const satisfies readonly CatalogManifestRecord[];
