import type { CatalogManifestRecord } from "@/domain/exercises/catalog-generator";

export const shouldersManifest = [
  {
    slug: "seated-dumbbell-shoulder-press",
    name: "Seated dumbbell shoulder press",
    role: "compound",
    loggingKind: "weight_reps",
    requiredEquipment: ["dumbbells", "bench"],
    movementFamily: "shoulder-press",
    primaryMuscles: ["deltoids", "triceps"],
    aliases: ["seated DB press", "dumbbell overhead press"],
    instructions: [
      "Sit against an upright bench with both feet planted.",
      "Start with the weights near shoulder height and wrists stacked.",
      "Press overhead smoothly, then return to the start under control.",
    ],
  },
  {
    slug: "standing-dumbbell-shoulder-press",
    name: "Standing dumbbell shoulder press",
    role: "compound",
    loggingKind: "weight_reps",
    requiredEquipment: ["dumbbells"],
    movementFamily: "shoulder-press",
    primaryMuscles: ["deltoids", "triceps"],
    aliases: ["standing DB press", "dumbbell military press"],
    instructions: [
      "Stand balanced with the dumbbells held near shoulder height.",
      "Press both weights overhead while the torso stays stacked.",
      "Lower the dumbbells to the shoulders under control before repeating.",
    ],
  },
  {
    slug: "arnold-press",
    name: "Arnold press",
    role: "compound",
    loggingKind: "weight_reps",
    requiredEquipment: ["dumbbells", "bench"],
    movementFamily: "shoulder-press",
    primaryMuscles: ["deltoids", "triceps"],
    aliases: ["Arnold dumbbell press", "rotating shoulder press"],
    instructions: [
      "Sit securely with the dumbbells in front of the shoulders and palms inward.",
      "Rotate the palms forward as the weights travel overhead.",
      "Reverse the path slowly to return the dumbbells in front of the shoulders.",
    ],
  },
  {
    slug: "dumbbell-lateral-raise",
    name: "Dumbbell lateral raise",
    role: "accessory",
    loggingKind: "weight_reps",
    requiredEquipment: ["dumbbells"],
    movementFamily: "lateral-raise",
    primaryMuscles: ["side deltoids"],
    aliases: ["side lateral raise", "DB side raise"],
    instructions: [
      "Stand tall with the dumbbells resting at the sides.",
      "Raise the arms out to the sides with the elbows softly bent.",
      "Lower the weights slowly without swinging the torso.",
    ],
  },
  {
    slug: "leaning-dumbbell-lateral-raise",
    name: "Leaning dumbbell lateral raise",
    role: "accessory",
    loggingKind: "weight_reps",
    requiredEquipment: ["dumbbells", "rack"],
    movementFamily: "lateral-raise",
    primaryMuscles: ["side deltoids"],
    aliases: ["lean-away lateral raise", "supported lateral raise"],
    instructions: [
      "Hold the rack with one hand and lean away with both feet planted.",
      "Raise the outside dumbbell to the side without rotating the torso.",
      "Lower the weight under control, finish the side, then switch.",
    ],
  },
  {
    slug: "dumbbell-front-raise",
    name: "Dumbbell front raise",
    role: "accessory",
    loggingKind: "weight_reps",
    requiredEquipment: ["dumbbells"],
    movementFamily: "front-raise",
    primaryMuscles: ["front deltoids"],
    aliases: ["DB front raise", "dumbbell forward raise"],
    instructions: [
      "Stand tall with the dumbbells in front of the thighs.",
      "Lift the weights forward with softly bent elbows and a quiet torso.",
      "Lower the dumbbells slowly to the starting position.",
    ],
  },
  {
    slug: "barbell-overhead-press",
    name: "Barbell overhead press",
    role: "compound",
    loggingKind: "weight_reps",
    requiredEquipment: ["barbell", "plates", "rack"],
    movementFamily: "shoulder-press",
    primaryMuscles: ["deltoids", "triceps", "upper back"],
    aliases: ["strict press", "standing barbell press"],
    instructions: [
      "Unrack the bar at shoulder height and stand with the wrists stacked.",
      "Press overhead while keeping the legs still and the torso balanced.",
      "Lower the bar to the shoulders under control before reracking.",
    ],
  },
  {
    slug: "barbell-push-press",
    name: "Barbell push press",
    role: "compound",
    loggingKind: "weight_reps",
    requiredEquipment: ["barbell", "plates", "rack"],
    movementFamily: "push-press",
    primaryMuscles: ["deltoids", "triceps", "quads", "glutes"],
    aliases: ["push press", "barbell leg-drive press"],
    instructions: [
      "Unrack the bar at the shoulders and set a balanced stance.",
      "Dip through the knees, then drive the bar overhead as the legs extend.",
      "Control the bar back to the shoulders and reset before repeating.",
    ],
  },
  {
    slug: "dumbbell-z-press",
    name: "Dumbbell Z press",
    role: "compound",
    loggingKind: "weight_reps",
    requiredEquipment: ["dumbbells"],
    movementFamily: "shoulder-press",
    primaryMuscles: ["deltoids", "triceps", "core"],
    aliases: ["seated floor dumbbell press", "DB Z press"],
    instructions: [
      "Sit tall on the floor with the legs extended and dumbbells at the shoulders.",
      "Press the weights overhead without leaning the torso back.",
      "Lower the dumbbells smoothly while keeping the seated position steady.",
    ],
  },
  {
    slug: "dumbbell-upright-row",
    name: "Dumbbell upright row",
    role: "accessory",
    loggingKind: "weight_reps",
    requiredEquipment: ["dumbbells"],
    movementFamily: "upright-row",
    primaryMuscles: ["side deltoids", "traps"],
    aliases: ["DB upright row", "dumbbell vertical row"],
    instructions: [
      "Stand with the dumbbells together in front of the thighs.",
      "Lead with the elbows as the weights travel close to the torso.",
      "Stop at a comfortable height and lower the dumbbells slowly.",
    ],
  },
  {
    slug: "barbell-upright-row",
    name: "Barbell upright row",
    role: "accessory",
    loggingKind: "weight_reps",
    requiredEquipment: ["barbell", "plates"],
    movementFamily: "upright-row",
    primaryMuscles: ["side deltoids", "traps"],
    aliases: ["upright barbell row", "barbell vertical row"],
    instructions: [
      "Stand tall with the bar held in front of the thighs.",
      "Guide the bar upward close to the torso with the elbows leading.",
      "Stop at a comfortable height and lower the bar under control.",
    ],
  },
] as const satisfies readonly CatalogManifestRecord[];
